logger:
  enable: true
  pretty_backtrace: false
  level: info
  format: json

server:
  port: "{{ get_env(name=\"PORT\", default=\"8080\") }}"
  binding: 0.0.0.0
  host: "{{ get_env(name=\"HOST\", default=\"http://localhost\") }}"
  middlewares:
    compression:
      enable: true
    etag:
      enable: true
    limit_payload:
      enable: true
      body_limit: 5mb
    cors:
      enable: true

workers:
  mode: BackgroundQueue

mailer:
  smtp:
    enable: false

database:
  uri: "{{ get_env(name=\"DATABASE_URL\") }}"
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 2
  max_connections: 20
  auto_migrate: false
  dangerously_truncate: false
  dangerously_recreate: false

queue:
  kind: Postgres
  uri: "{{ get_env(name=\"DATABASE_URL\") }}"
  dangerously_flush: false

auth:
  jwt:
    secret: "{{ get_env(name=\"JWT_SECRET\") }}"
    expiration: 604800
