//! RESTful API implementation with Axum.
//!
//! This module wires the HTTP surface together:
//! [`ApiDoc`](crate::api::rest::ApiDoc) is the utoipa OpenAPI document,
//! [`create_router`](crate::api::rest::create_router) mounts every
//! handler under `/api/v1` (plus `/metrics.prom` and the Swagger UI at
//! `/swagger-ui`), and [`serve`](crate::api::rest::serve) binds the
//! configured host/port and runs the server. Handlers live in
//! [`handlers`](crate::api::rest::handlers), shared services in
//! [`state`](crate::api::rest::state)
//! ([`AppState`](crate::api::rest::AppState)).
//!
//! ```ignore
//! use event_service::api::rest::{create_router, serve, AppState};
//!
//! // `state` is an AppState built from a DB connection + services.
//! let app = create_router(state.clone());   // an axum::Router
//! serve(state).await?;                        // binds and serves
//! ```

use axum::{
    Router,
    routing::{delete, get, post, put},
};
use tower_http::cors::CorsLayer;
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

/// REST endpoint handlers and their request/response DTOs.
pub mod handlers;
/// Route-organization helpers.
pub mod routes;
/// Shared application state ([`AppState`]) passed to every handler.
pub mod state;

pub use state::AppState;

/// `OpenAPI` 3.0 document for the service, generated by utoipa from the
/// annotated handlers and model schemas. Served as JSON at
/// `/api-docs/openapi.json` and rendered by the Swagger UI.
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Event Service API",
        version = "0.1.0",
        description = "RESTful API for events (schema.org/Event): CRUD, matching, deduplication, search, and privacy",
        contact(
            name = "Event Service Development Team",
            email = "support@example.com"
        )
    ),
    paths(
        handlers::health_check,
        handlers::metrics_prom,
        handlers::create_event,
        handlers::get_event,
        handlers::update_event,
        handlers::delete_event,
        handlers::search_events,
        handlers::match_event,
        handlers::check_duplicates,
        handlers::merge_events,
        handlers::batch_deduplicate,
        handlers::export_event_data,
        handlers::get_event_masked,
        handlers::get_event_audit_logs,
        handlers::get_recent_audit_logs,
        handlers::get_user_audit_logs,
    ),
    components(
        schemas(
            crate::models::Event,
            crate::models::EventLink,
            crate::models::event::LinkType,
            crate::models::Organization,
            crate::models::Identifier,
            crate::models::identifier::IdentifierType,
            crate::models::identifier::IdentifierUse,
            crate::models::Address,
            crate::models::AddressUse,
            crate::models::ContactPoint,
            crate::models::ContactPointSystem,
            crate::models::ContactPointUse,
            crate::models::Location,
            crate::models::Place,
            crate::models::VirtualLocation,
            crate::models::Party,
            crate::models::PartyKind,
            crate::models::Reference,
            crate::models::Offer,
            crate::models::OfferAvailability,
            crate::models::EventStatus,
            crate::models::EventAttendanceMode,
            crate::models::EventType,
            crate::models::MergeRequest,
            crate::models::MergeResponse,
            crate::models::MergeRecord,
            crate::models::MergeStatus,
            crate::models::BatchDeduplicationRequest,
            crate::models::BatchDeduplicationResponse,
            crate::models::ReviewQueueItem,
            crate::models::ReviewStatus,
            crate::models::Consent,
            crate::models::ConsentType,
            crate::models::ConsentStatus,
            crate::matching::MatchScoreBreakdown,
            crate::api::ApiResponse::<crate::models::Event>,
            crate::api::ApiError,
            handlers::HealthResponse,
            handlers::CreateEventRequest,
            handlers::SearchQuery,
            handlers::SearchResponse,
            handlers::MatchRequest,
            handlers::MatchResponse,
            handlers::MatchResultsResponse,
            handlers::DuplicateCheckResponse,
            handlers::AuditLogQuery,
            handlers::UserAuditLogQuery,
        )
    ),
    tags(
        (name = "health", description = "Health check endpoint"),
        (name = "observability", description = "Prometheus metrics endpoint"),
        (name = "events", description = "Event management endpoints"),
        (name = "search", description = "Event search endpoints"),
        (name = "matching", description = "Event matcher endpoints"),
        (name = "deduplication", description = "Duplicate detection, review, and merge endpoints"),
        (name = "privacy", description = "Data masking, export, and consent endpoints"),
        (name = "audit", description = "Audit log query endpoints"),
    )
)]
pub struct ApiDoc;

/// Build the full `axum::Router`: every `/api/v1/*` route bound to its
/// handler with shared [`AppState`], plus the top-level
/// `/metrics.prom` scrape endpoint, the Swagger UI, and a permissive
/// CORS layer.
pub fn create_router(state: AppState) -> Router {
    use crate::api::fhir::handlers as fhir;

    let api_routes = Router::new()
        // Health
        .route("/health", get(handlers::health_check))
        // Event CRUD
        .route("/events", post(handlers::create_event))
        .route("/events/{id}", get(handlers::get_event))
        .route("/events/{id}", put(handlers::update_event))
        .route("/events/{id}", delete(handlers::delete_event))
        // Search
        .route("/events/search", get(handlers::search_events))
        // Matching
        .route("/events/match", post(handlers::match_event))
        // Duplicate detection & deduplication
        .route("/events/check-duplicates", post(handlers::check_duplicates))
        .route("/events/merge", post(handlers::merge_events))
        .route("/events/deduplicate", post(handlers::batch_deduplicate))
        // Privacy
        .route("/events/{id}/export", get(handlers::export_event_data))
        .route("/events/{id}/masked", get(handlers::get_event_masked))
        // Audit
        .route("/events/{id}/audit", get(handlers::get_event_audit_logs))
        .route("/audit/recent", get(handlers::get_recent_audit_logs))
        .route("/audit/user", get(handlers::get_user_audit_logs))
        .with_state(state);

    // FHIR R5 stub surface: every `/fhir/Event*` route returns `501 Not
    // Implemented` with an `OperationOutcome` body (spec §6.8). Bound
    // here so an unmatched request yields `501`, not `404`. The stub
    // handlers are sync `fn`s, so wrap each in an async closure.
    let fhir_routes = Router::new()
        .route(
            "/Event",
            get(|| async { fhir::search_events() }).post(|| async { fhir::create_event() }),
        )
        .route(
            "/Event/{id}",
            get(|| async { fhir::get_event() })
                .put(|| async { fhir::update_event() })
                .delete(|| async { fhir::delete_event() }),
        );

    Router::new()
        // All entity/audit routes live under `/api/v1`; `/metrics.prom`
        // sits at the root so a default Prometheus scrape config finds
        // it, and the Swagger UI is mounted at the root as well.
        .nest("/api/v1", api_routes)
        .nest("/fhir", fhir_routes)
        .route("/metrics.prom", get(handlers::metrics_prom))
        .merge(SwaggerUi::new("/swagger-ui").url("/api-docs/openapi.json", ApiDoc::openapi()))
        // Permissive CORS: this is a backend service fronted elsewhere;
        // tighten if exposed directly to browsers.
        .layer(CorsLayer::permissive())
}

/// Native loco controller routes (idiomatic path): the `/api/v1` surface
/// as a loco `Routes`; handlers extract `AppState` from the `AppContext`
/// shared store via `FromRef`. `create_router` is retained for the
/// integration tests. The root `/metrics.prom` route is [`metrics_routes`].
#[must_use]
pub fn events_routes() -> loco_rs::controller::Routes {
    use loco_rs::prelude::{Routes, get, post};
    Routes::new()
        .prefix("/api/v1")
        .add("/health", get(handlers::health_check))
        .add("/events", post(handlers::create_event))
        .add(
            "/events/{id}",
            get(handlers::get_event)
                .put(handlers::update_event)
                .delete(handlers::delete_event),
        )
        .add("/events/search", get(handlers::search_events))
        .add("/events/match", post(handlers::match_event))
        .add("/events/check-duplicates", post(handlers::check_duplicates))
        .add("/events/merge", post(handlers::merge_events))
        .add("/events/deduplicate", post(handlers::batch_deduplicate))
        .add("/events/{id}/export", get(handlers::export_event_data))
        .add("/events/{id}/masked", get(handlers::get_event_masked))
        .add("/events/{id}/audit", get(handlers::get_event_audit_logs))
        .add("/audit/recent", get(handlers::get_recent_audit_logs))
        .add("/audit/user", get(handlers::get_user_audit_logs))
}

/// Root-level Prometheus scrape route (`GET /metrics.prom`).
#[must_use]
pub fn metrics_routes() -> loco_rs::controller::Routes {
    use loco_rs::prelude::{Routes, get};
    Routes::new().add("/metrics.prom", get(handlers::metrics_prom))
}

/// FHIR R5 stub routes (`/fhir/Event*`): every method returns
/// `501 Not Implemented` with an `OperationOutcome` body (spec §6.8).
/// Bound so an unmatched request yields `501`, not `404`.
#[must_use]
pub fn fhir_routes() -> loco_rs::controller::Routes {
    use crate::api::fhir::handlers as fhir;
    use loco_rs::prelude::{Routes, get, post};
    Routes::new()
        .prefix("/fhir")
        .add("/Event", get(|| async { fhir::search_events() }))
        .add("/Event", post(|| async { fhir::create_event() }))
        .add(
            "/Event/{id}",
            get(|| async { fhir::get_event() })
                .put(|| async { fhir::update_event() })
                .delete(|| async { fhir::delete_event() }),
        )
}
