//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
//!
//! Generated entity definitions. Regenerated by `sea-orm-codegen`, so
//! the crate-wide `deny(missing_docs)` is relaxed here rather than
//! hand-annotating fields that codegen would overwrite.
#![allow(missing_docs)]

pub mod prelude;
pub mod sessions;
pub mod users;
