//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0 — the `users`
//! table backing passwordless magic-link accounts. Domain logic lives in
//! [`crate::models::users`]; this file is the generated row shape.

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// A `users` row. Holds the magic-link credentials plus the loco-scaffold
/// password/reset fields (unused by the passwordless flow). Note that
/// `password`/`api_key`/`*_token` are **secrets**: views never serialise
/// them (see [`crate::views::auth`]).
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    /// Row creation time.
    pub created_at: DateTimeWithTimeZone,
    /// Last update time.
    pub updated_at: DateTimeWithTimeZone,
    /// Internal autoincrement primary key (never exposed externally).
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Public id — the stable external UUID used in tokens (`sub`) and
    /// URLs; assigned in `before_save`, not by the caller.
    pub pid: Uuid,
    /// Account email (unique). Anonymised to a tombstone on GDPR erasure.
    #[sea_orm(unique)]
    pub email: String,
    /// Password hash. **Unusable** in the passwordless flow — holds the
    /// hash of a random value no login path checks. Never serialised.
    pub password: String,
    /// Per-user api key (unique), assigned in `before_save`. Secret.
    #[sea_orm(unique)]
    pub api_key: String,
    /// Display name. Anonymised to a tombstone on GDPR erasure.
    pub name: String,
    /// Password-reset token (loco scaffold; unused by passwordless flow).
    pub reset_token: Option<String>,
    /// When the reset token was sent (loco scaffold; unused).
    pub reset_sent_at: Option<DateTimeWithTimeZone>,
    /// Email-verification token (loco scaffold; unused — magic-link
    /// redemption verifies the email instead).
    pub email_verification_token: Option<String>,
    /// When the verification email was sent (loco scaffold; unused).
    pub email_verification_sent_at: Option<DateTimeWithTimeZone>,
    /// When the email was verified, if ever (set on first magic-link
    /// redemption).
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    /// Live, single-use magic-link token. Secret; cleared on redemption
    /// and on erasure; never serialised into a response.
    pub magic_link_token: Option<String>,
    /// Expiry of the live magic-link token (a few minutes after issue).
    pub magic_link_expiration: Option<DateTimeWithTimeZone>,
    /// Set by GDPR Art. 17 erasure: when present the account is
    /// soft-deleted (and its `email`/`name` anonymised to a tombstone),
    /// and every read path must treat the user as gone.
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
