#!/usr/bin/env bash
#
# Regenerate .github/dependabot.yml from the live tree.
#
# Dependabot's `cargo` ecosystem does not recurse into nested workspaces
# (a crate's `migration/` and `fuzz/` sub-crates are their own
# `Cargo.toml`, exactly as `scripts/ci-crates.sh` already treats them for
# CI), so every one of them needs its own `directory:` entry — there is
# no way to point Dependabot at "the repo" and have it find them itself.
# This script reuses the same discovery `find` as ci-crates.sh (Rust) plus
# an equivalent one for `package.json` (the SvelteKit front-ends) so the
# two never drift apart, and prints a ready-to-commit dependabot.yml.
#
# Usage:
#   scripts/dependabot-generate.sh > .github/dependabot.yml
#
# Re-run and commit the diff whenever a crate or front-end is added,
# removed, or moved.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT}"

cargo_dirs="$(
  find . \
       \( -name target -o -name node_modules -o -name .svelte-kit -o -name .git \) -prune \
       -o -name Cargo.toml -print \
    | xargs -n1 dirname \
    | sed 's|^\.$|/|; s|^\./|/|' \
    | sort -u
)"

npm_dirs="$(
  find . \
       \( -name target -o -name node_modules -o -name .svelte-kit -o -name .git \) -prune \
       -o -name package.json -print \
    | xargs -n1 dirname \
    | sed 's|^\.$|/|; s|^\./|/|' \
    | sort -u
)"

cat <<'HEADER'
# Generated by scripts/dependabot-generate.sh — do not hand-edit.
#
# This repository has no root Cargo.toml or package.json (each of the
# ~55 crates and the SvelteKit front-ends is its own workspace/package,
# per AGENTS.md), so Dependabot needs one `directory:` entry per
# workspace rather than a single entry at "/". Re-run the generator and
# commit the diff whenever a crate or front-end is added, removed, or
# moved: scripts/dependabot-generate.sh > .github/dependabot.yml
version: 2
updates:
HEADER

while IFS= read -r dir; do
  [[ -z "${dir}" ]] && continue
  cat <<ENTRY
  - package-ecosystem: "cargo"
    directory: "${dir}"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "rust"
    groups:
      routine:
        update-types:
          - "minor"
          - "patch"
ENTRY
done <<< "${cargo_dirs}"

while IFS= read -r dir; do
  [[ -z "${dir}" ]] && continue
  cat <<ENTRY
  - package-ecosystem: "npm"
    directory: "${dir}"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"
    groups:
      routine:
        update-types:
          - "minor"
          - "patch"
ENTRY
done <<< "${npm_dirs}"

cat <<'FOOTER'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
FOOTER
