// Typed client for the Loco JSON API at /api/*.
//
// Base URL comes from VITE_API_BASE_URL. It defaults to '' (relative),
// so requests are same-origin and the dev server proxies /api to the
// Loco app — this keeps the HttpOnly session cookie first-party (see
// spec/auth.md). Set VITE_API_BASE_URL to talk to a different origin.
//
// Every request sends credentials so the session cookie flows.
//
// Convention: the API speaks snake_case on the wire; this client
// converts to/from camelCase at the boundary so the rest of the app
// can pretend the field names were camelCase all along.

import type {
    Alert,
    Building,
    Cabinet,
    Folder,
    MoveEvent,
    Patient,
    Presence,
    Room,
    Stats,
    User,
    Volume,
    Worker
} from '$lib/store/types';
import type { components } from './schema';

const DEFAULT_BASE = '';

/**
 * Resolve the API origin. Reads `VITE_API_BASE_URL` (trailing slash
 * trimmed); falls back to '' so requests are same-origin and the dev
 * server proxies `/api` to Loco, keeping the session cookie first-party.
 * @returns The base URL prefix ('' for same-origin).
 */
function baseUrl(): string {
    const fromEnv =
        typeof import.meta !== 'undefined' &&
        (import.meta as { env?: { VITE_API_BASE_URL?: string } }).env?.VITE_API_BASE_URL;
    return (fromEnv && fromEnv.replace(/\/$/, '')) || DEFAULT_BASE;
}

/**
 * Error thrown by every failed API call.
 *
 * Carries the HTTP `status` (0 when the request never reached the server,
 * e.g. a network failure) and the parsed response `body` (when any), so
 * callers can branch on status (401 / 404 / 422 …) and read structured
 * field errors out of the body.
 */
export class ApiError extends Error {
    /**
     * @param message - Human-readable error message (server `error` field
     *   when present, else a synthesised description).
     * @param status - HTTP status code, or 0 if the request never completed.
     * @param body - Parsed JSON response body, or null.
     */
    constructor(
        message: string,
        public readonly status: number,
        public readonly body: unknown
    ) {
        super(message);
        this.name = 'ApiError';
    }
}

interface RequestOpts {
    method?: 'GET' | 'POST' | 'PATCH' | 'DELETE';
    body?: unknown;
    fetchImpl?: typeof fetch;
}

/**
 * Core fetch wrapper used by every endpoint below.
 *
 * Prefixes {@link baseUrl}, JSON-encodes the body (and only sets the
 * content-type header when there is one), always sends credentials so the
 * HttpOnly session cookie flows, parses the JSON response, and converts any
 * transport failure or non-2xx response into an {@link ApiError}.
 *
 * In `+page.ts` load functions, pass SvelteKit's `fetch` via
 * `opts.fetchImpl` so requests participate in SSR/load dedup + relative URLs.
 *
 * @typeParam T - The expected (wire-shaped) response type.
 * @param path - Request path beginning with `/api/...`.
 * @param opts - Method, JSON body, and optional fetch implementation.
 * @returns The parsed response body as `T`.
 * @throws {ApiError} On network failure (status 0) or any non-2xx response.
 */
async function request<T>(path: string, opts: RequestOpts = {}): Promise<T> {
    const f = opts.fetchImpl ?? fetch;
    const init: RequestInit = {
        method: opts.method ?? 'GET',
        headers: opts.body ? { 'content-type': 'application/json' } : undefined,
        body: opts.body ? JSON.stringify(opts.body) : undefined,
        // Send the HttpOnly session cookie on every request.
        credentials: 'include'
    };
    let response: Response;
    try {
        response = await f(`${baseUrl()}${path}`, init);
    } catch (e) {
        throw new ApiError(
            `Cannot reach Case Tracking API at ${baseUrl()}${path}: ${(e as Error).message}`,
            0,
            null
        );
    }
    const text = await response.text();
    const body = text ? (JSON.parse(text) as unknown) : null;
    if (!response.ok) {
        const message =
            (body as { error?: string } | null)?.error ??
            `Request to ${path} failed with HTTP ${response.status}`;
        throw new ApiError(message, response.status, body);
    }
    return body as T;
}

// ---------------------------------------------------------------------------
// snake_case → camelCase mappers
//
// One `toX` function per resource translates the wire (snake_case) shape
// into the app's camelCase domain type. They are the single boundary where
// field renaming happens, so the rest of the app never sees snake_case.
// A subset is re-exported at the bottom of the file for unit testing.
// ---------------------------------------------------------------------------

// Wire (snake_case) shapes come from the OpenAPI schema — the single
// source of truth, generated by `npm run gen:api` into ./schema. Response
// fields are always present, so `Required<>` drops the schema's optional
// markers while keeping nullability.
type ApiPatient = Required<components['schemas']['Patient']>;
type ApiFolder = Required<components['schemas']['Folder']>;
type ApiVolume = Required<components['schemas']['Volume']>;
type ApiMove = Required<components['schemas']['Move']>;
type ApiPlace = Required<components['schemas']['Place']>;
type ApiWorker = Required<components['schemas']['Worker']>;
type ApiPresence = Required<components['schemas']['Presence']>;

type ApiCabinet = ApiPlace & { folder_count: number };
type ApiVolumeShow = ApiVolume & { folders: ApiFolder[]; history: ApiMove[] };
type ApiPlaceHistory = ApiPlace & { presences: ApiPresence[] };
type ApiPlaceShow = ApiPlace & { folders: ApiFolder[] };

interface ApiWorkerShow {
    worker: ApiWorker;
    moved_folders: ApiFolder[];
    patient_folders: ApiFolder[];
    moves: ApiMove[];
}

interface ApiList<T> {
    items: T[];
    query?: string;
}

interface ApiPlacesIndex {
    query: string | null;
    kind: string | null;
    buildings: ApiPlace[];
    rooms: ApiPlace[];
    cabinets: ApiCabinet[];
}

interface ApiPatientShow {
    patient: ApiPatient | null;
    folders: ApiFolder[];
    history: ApiMove[];
    nhs_number: string;
    patient_service_match: boolean;
}

interface ApiStats {
    patients: number;
    folders: { total: number; in_cabinet: number; in_transit: number };
    places: { buildings: number; rooms: number; cabinets: number };
    moves_24h: number;
}

function toPatient(p: ApiPatient): Patient {
    return {
        id: p.id,
        nhsNumber: p.nhs_number,
        name: p.name,
        dateOfBirth: p.date_of_birth,
        folderCount: p.folder_count,
        source: p.source
    };
}

function toFolder(f: ApiFolder): Folder {
    return {
        id: f.id,
        title: f.title,
        patientId: f.patient_id,
        nhsNumber: f.nhs_number,
        patientName: f.patient_name,
        cabinetId: f.cabinet_id,
        cabinetLabel: f.cabinet_label,
        status: f.status,
        lastMovedAt: f.last_moved_at,
        notes: f.notes,
        volumeId: f.volume_id,
        volumeTitle: f.volume_title
    };
}

type ApiAlert = Required<components['schemas']['Alert']>;

function toAlert(a: ApiAlert): Alert {
    return {
        moveId: a.move_id,
        folderId: a.folder_id,
        folderTitle: a.folder_title,
        patientName: a.patient_name,
        nhsNumber: a.nhs_number,
        fromBuilding: a.from_building,
        toBuilding: a.to_building,
        fromCabinetLabel: a.from_cabinet_label,
        toCabinetLabel: a.to_cabinet_label,
        movedBy: a.moved_by,
        movedAt: a.moved_at,
        reason: a.reason
    };
}

function toVolume(v: ApiVolume): Volume {
    return {
        id: v.id,
        title: v.title,
        patientId: v.patient_id,
        nhsNumber: v.nhs_number,
        patientName: v.patient_name,
        cabinetId: v.cabinet_id,
        cabinetLabel: v.cabinet_label,
        status: v.status,
        folderCount: v.folder_count
    };
}

/** A volume plus its current folders and move history (the show/mutate shape). */
export interface VolumeDetail {
    volume: Volume;
    folders: Folder[];
    history: MoveEvent[];
}

function toVolumeDetail(body: ApiVolumeShow): VolumeDetail {
    const { folders, history, ...vol } = body;
    return {
        volume: toVolume(vol),
        folders: folders.map(toFolder),
        history: history.map(toMove)
    };
}

function toMove(m: ApiMove): MoveEvent {
    return {
        id: m.id,
        folderId: m.folder_id,
        folderTitle: m.folder_title,
        patientId: m.patient_id,
        nhsNumber: m.nhs_number,
        patientName: m.patient_name,
        fromCabinetId: m.from_cabinet_id,
        fromCabinetLabel: m.from_cabinet_label,
        toCabinetId: m.to_cabinet_id,
        toCabinetLabel: m.to_cabinet_label,
        workerId: m.worker_id,
        movedBy: m.moved_by,
        workerRole: m.worker_role,
        movedAt: m.moved_at,
        reason: m.reason
    };
}

function toBuilding(p: ApiPlace): Building {
    return { id: p.id, name: p.name, description: p.description };
}

function toRoom(p: ApiPlace): Room {
    return {
        id: p.id,
        name: p.name,
        buildingId: p.contained_in_place,
        description: p.description
    };
}

function toCabinet(p: ApiCabinet): Cabinet {
    return {
        id: p.id,
        label: p.name,
        roomId: p.contained_in_place,
        capacity: p.capacity,
        description: p.description,
        folderCount: p.folder_count,
        containerPath: p.container_path
    };
}

function toWorker(w: ApiWorker): Worker {
    return { id: w.id, name: w.name, role: w.role };
}

function toPresence(p: ApiPresence): Presence {
    return {
        folderId: p.folder_id,
        folderTitle: p.folder_title,
        patientId: p.patient_id,
        nhsNumber: p.nhs_number,
        patientName: p.patient_name,
        cabinetId: p.cabinet_id,
        cabinetLabel: p.cabinet_label,
        enteredAt: p.entered_at,
        leftAt: p.left_at,
        enteredReason: p.entered_reason,
        leftReason: p.left_reason
    };
}

function toStats(s: ApiStats): Stats {
    return {
        patients: s.patients,
        folders: {
            total: s.folders.total,
            inCabinet: s.folders.in_cabinet,
            inTransit: s.folders.in_transit
        },
        places: s.places,
        moves24h: s.moves_24h
    };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Per-call options for read endpoints. Pass SvelteKit's `fetch` from a
 * load function so the request joins SSR/load dedup and uses relative URLs.
 */
export interface FetchOpts {
    fetch?: typeof fetch;
}

interface ApiUser {
    email: string;
    name: string;
    role: string | null;
}

/**
 * The typed API client: one namespace per resource (`auth`, `folders`,
 * `patients`, `places`, `volumes`, `workers`, `moves`) plus top-level
 * `stats` / `alerts`. Every method goes through {@link request} and returns
 * camelCase domain types (mapped from the snake_case wire shapes), throwing
 * {@link ApiError} on failure.
 */
export const api = {
    auth: {
        /// Ask for a magic-link email. Always resolves (the API answers
        /// 200 whether or not the email is known). In dev/test the
        /// response carries the link so it can be shown / clicked.
        async requestLink(
            email: string,
            opts: FetchOpts = {}
        ): Promise<{ sent: boolean; magicLink: string | null }> {
            const body = await request<{ sent: boolean; magic_link?: string | null }>(
                '/api/auth/request',
                { method: 'POST', body: { email }, fetchImpl: opts.fetch }
            );
            return { sent: body.sent, magicLink: body.magic_link ?? null };
        },

        /// Exchange a magic token for a session (sets the HttpOnly cookie).
        async verify(token: string, opts: FetchOpts = {}): Promise<User> {
            const body = await request<{ user: ApiUser }>('/api/auth/verify', {
                method: 'POST',
                body: { token },
                fetchImpl: opts.fetch
            });
            return body.user;
        },

        /// The signed-in user. Throws `ApiError` with status 401 when not
        /// authenticated.
        async me(opts: FetchOpts = {}): Promise<User> {
            const body = await request<{ user: ApiUser }>('/api/auth/me', {
                fetchImpl: opts.fetch
            });
            return body.user;
        },

        /// End the session (clears the cookie).
        async logout(opts: FetchOpts = {}): Promise<void> {
            await request<null>('/api/auth/logout', { method: 'POST', fetchImpl: opts.fetch });
        }
    },

    async stats(opts: FetchOpts = {}): Promise<Stats> {
        const body = await request<ApiStats>('/api/stats', { fetchImpl: opts.fetch });
        return toStats(body);
    },

    alerts: {
        async list(opts: FetchOpts = {}): Promise<Alert[]> {
            const body = await request<ApiList<ApiAlert>>('/api/alerts', {
                fetchImpl: opts.fetch
            });
            return body.items.map(toAlert);
        }
    },

    folders: {
        async list(
            params: { q?: string; nhsNumber?: string } = {},
            opts: FetchOpts = {}
        ): Promise<{ items: Folder[]; query?: string }> {
            const qs = new URLSearchParams();
            if (params.q) qs.set('q', params.q);
            if (params.nhsNumber) qs.set('nhs_number', params.nhsNumber);
            const suffix = qs.toString() ? `?${qs}` : '';
            const body = await request<ApiList<ApiFolder>>(`/api/folders${suffix}`, {
                fetchImpl: opts.fetch
            });
            return { items: body.items.map(toFolder), query: body.query };
        },

        async show(id: string, opts: FetchOpts = {}): Promise<Folder> {
            const body = await request<ApiFolder>(`/api/folders/${encodeURIComponent(id)}`, {
                fetchImpl: opts.fetch
            });
            return toFolder(body);
        },

        async history(id: string, opts: FetchOpts = {}): Promise<MoveEvent[]> {
            const body = await request<ApiList<ApiMove>>(
                `/api/folders/${encodeURIComponent(id)}/history`,
                { fetchImpl: opts.fetch }
            );
            return body.items.map(toMove);
        },

        async create(input: {
            nhsNumber: string;
            patientName?: string;
            dateOfBirth?: string;
            title: string;
            cabinetId?: string | null;
            notes?: string;
        }): Promise<Folder> {
            const body = await request<ApiFolder>('/api/folders', {
                method: 'POST',
                body: {
                    nhs_number: input.nhsNumber,
                    patient_name: input.patientName ?? null,
                    date_of_birth: input.dateOfBirth ?? null,
                    title: input.title,
                    cabinet_id: input.cabinetId ?? null,
                    notes: input.notes ?? null
                }
            });
            return toFolder(body);
        }
    },

    patients: {
        async list(
            params: { q?: string } = {},
            opts: FetchOpts = {}
        ): Promise<{ items: Patient[]; query?: string }> {
            const qs = params.q ? `?q=${encodeURIComponent(params.q)}` : '';
            const body = await request<ApiList<ApiPatient>>(`/api/patients${qs}`, {
                fetchImpl: opts.fetch
            });
            return { items: body.items.map(toPatient), query: body.query };
        },

        async show(
            nhs: string,
            opts: FetchOpts = {}
        ): Promise<{
            patient: Patient | null;
            folders: Folder[];
            history: MoveEvent[];
            nhsNumber: string;
            patientServiceMatch: boolean;
        }> {
            const body = await request<ApiPatientShow>(
                `/api/patients/${encodeURIComponent(nhs)}`,
                { fetchImpl: opts.fetch }
            );
            return {
                patient: body.patient ? toPatient(body.patient) : null,
                folders: body.folders.map(toFolder),
                history: body.history.map(toMove),
                nhsNumber: body.nhs_number,
                patientServiceMatch: body.patient_service_match
            };
        }
    },

    places: {
        async list(
            params: { q?: string; kind?: 'building' | 'room' | 'cabinet' } = {},
            opts: FetchOpts = {}
        ): Promise<{
            buildings: Building[];
            rooms: Room[];
            cabinets: Cabinet[];
            query: string | null;
            kind: string | null;
        }> {
            const qs = new URLSearchParams();
            if (params.q) qs.set('q', params.q);
            if (params.kind) qs.set('kind', params.kind);
            const suffix = qs.toString() ? `?${qs}` : '';
            const body = await request<ApiPlacesIndex>(`/api/places${suffix}`, {
                fetchImpl: opts.fetch
            });
            return {
                buildings: body.buildings.map(toBuilding),
                rooms: body.rooms.map(toRoom),
                cabinets: body.cabinets.map(toCabinet),
                query: body.query,
                kind: body.kind
            };
        },

        async show(
            id: string,
            opts: FetchOpts = {}
        ): Promise<{ place: ApiPlace; folders: Folder[] }> {
            const body = await request<ApiPlaceShow>(`/api/places/${encodeURIComponent(id)}`, {
                fetchImpl: opts.fetch
            });
            const { folders, ...place } = body;
            return { place, folders: folders.map(toFolder) };
        },

        /// Folder presence history for a place. For a cabinet this is its
        /// own in/out timeline; a room/building aggregates its cabinets.
        async history(
            id: string,
            opts: FetchOpts = {}
        ): Promise<{ place: ApiPlace; presences: Presence[] }> {
            const body = await request<ApiPlaceHistory>(
                `/api/places/${encodeURIComponent(id)}/history`,
                { fetchImpl: opts.fetch }
            );
            const { presences, ...place } = body;
            return { place, presences: presences.map(toPresence) };
        },

        async create(input: {
            name: string;
            kind: 'building' | 'room' | 'cabinet';
            containedInPlace?: string | null;
            description?: string;
            capacity?: number | null;
        }): Promise<ApiPlace> {
            return request<ApiPlace>('/api/places', {
                method: 'POST',
                body: {
                    name: input.name,
                    kind: input.kind,
                    contained_in_place: input.containedInPlace ?? null,
                    description: input.description ?? null,
                    capacity: input.capacity ?? null
                }
            });
        }
    },

    volumes: {
        async list(
            params: { q?: string; nhsNumber?: string } = {},
            opts: FetchOpts = {}
        ): Promise<{ items: Volume[]; query?: string }> {
            const qs = new URLSearchParams();
            if (params.q) qs.set('q', params.q);
            if (params.nhsNumber) qs.set('nhs_number', params.nhsNumber);
            const suffix = qs.toString() ? `?${qs}` : '';
            const body = await request<ApiList<ApiVolume>>(`/api/volumes${suffix}`, {
                fetchImpl: opts.fetch
            });
            return { items: body.items.map(toVolume), query: body.query };
        },

        async show(id: string, opts: FetchOpts = {}): Promise<VolumeDetail> {
            const body = await request<ApiVolumeShow>(`/api/volumes/${encodeURIComponent(id)}`, {
                fetchImpl: opts.fetch
            });
            return toVolumeDetail(body);
        },

        async create(input: {
            nhsNumber: string;
            title: string;
            cabinetId?: string | null;
        }): Promise<Volume> {
            const body = await request<ApiVolume>('/api/volumes', {
                method: 'POST',
                body: {
                    nhs_number: input.nhsNumber,
                    title: input.title,
                    cabinet_id: input.cabinetId ?? null
                }
            });
            return toVolume(body);
        },

        async rename(id: string, title: string): Promise<VolumeDetail> {
            const body = await request<ApiVolumeShow>(`/api/volumes/${encodeURIComponent(id)}`, {
                method: 'PATCH',
                body: { title }
            });
            return toVolumeDetail(body);
        },

        async addFolder(id: string, folderId: string): Promise<VolumeDetail> {
            const body = await request<ApiVolumeShow>(
                `/api/volumes/${encodeURIComponent(id)}/folders`,
                { method: 'POST', body: { folder_id: folderId } }
            );
            return toVolumeDetail(body);
        },

        async removeFolder(id: string, folderId: string): Promise<VolumeDetail> {
            const body = await request<ApiVolumeShow>(
                `/api/volumes/${encodeURIComponent(id)}/folders/${encodeURIComponent(folderId)}`,
                { method: 'DELETE' }
            );
            return toVolumeDetail(body);
        },

        async move(
            id: string,
            input: {
                toCabinetId?: string | null;
                workerId?: string | null;
                movedBy?: string;
                reason?: string;
            }
        ): Promise<VolumeDetail> {
            const body = await request<ApiVolumeShow>(
                `/api/volumes/${encodeURIComponent(id)}/move`,
                {
                    method: 'POST',
                    body: {
                        to_cabinet_id: input.toCabinetId ?? null,
                        worker_id: input.workerId ?? null,
                        moved_by: input.movedBy ?? null,
                        reason: input.reason ?? null
                    }
                }
            );
            return toVolumeDetail(body);
        }
    },

    workers: {
        async list(
            params: { q?: string } = {},
            opts: FetchOpts = {}
        ): Promise<{ items: Worker[]; query?: string }> {
            const qs = params.q ? `?q=${encodeURIComponent(params.q)}` : '';
            const body = await request<ApiList<ApiWorker>>(`/api/workers${qs}`, {
                fetchImpl: opts.fetch
            });
            return { items: body.items.map(toWorker), query: body.query };
        },

        /// Worker detail: folders this worker moved, every folder of their
        /// patients (a superset), and their move log.
        async show(
            id: string,
            opts: FetchOpts = {}
        ): Promise<{
            worker: Worker;
            movedFolders: Folder[];
            patientFolders: Folder[];
            moves: MoveEvent[];
        }> {
            const body = await request<ApiWorkerShow>(`/api/workers/${encodeURIComponent(id)}`, {
                fetchImpl: opts.fetch
            });
            return {
                worker: toWorker(body.worker),
                movedFolders: body.moved_folders.map(toFolder),
                patientFolders: body.patient_folders.map(toFolder),
                moves: body.moves.map(toMove)
            };
        }
    },

    moves: {
        async list(
            params: { q?: string } = {},
            opts: FetchOpts = {}
        ): Promise<{ items: MoveEvent[]; query?: string }> {
            const qs = params.q ? `?q=${encodeURIComponent(params.q)}` : '';
            const body = await request<ApiList<ApiMove>>(`/api/moves${qs}`, {
                fetchImpl: opts.fetch
            });
            return { items: body.items.map(toMove), query: body.query };
        },

        async show(id: string, opts: FetchOpts = {}): Promise<MoveEvent> {
            const body = await request<ApiMove>(`/api/moves/${encodeURIComponent(id)}`, {
                fetchImpl: opts.fetch
            });
            return toMove(body);
        },

        async create(input: {
            folderId: string;
            toCabinetId?: string | null;
            workerId?: string | null;
            movedBy?: string;
            reason?: string;
        }): Promise<MoveEvent> {
            const body = await request<ApiMove>('/api/moves', {
                method: 'POST',
                body: {
                    folder_id: input.folderId,
                    to_cabinet_id: input.toCabinetId ?? null,
                    worker_id: input.workerId ?? null,
                    moved_by: input.movedBy ?? null,
                    reason: input.reason ?? null
                }
            });
            return toMove(body);
        }
    }
};

export { toBuilding, toCabinet, toFolder, toMove, toPatient, toRoom, toStats, toWorker };
