/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/healthz': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (no auth, never touches upstreams). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** @constant */
                            status?: 'ok';
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/auth/request': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a magic-link sign-in email. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Always 200 (no email enumeration). `magic_link` is present only in dev/test. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            sent?: boolean;
                            magic_link?: string | null;
                        };
                    };
                };
                422: components['responses']['Validation'];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/auth/verify': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a magic token for a session (sets the cts_session cookie). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Session established. */
                200: {
                    headers: {
                        /** @description cts_session=<jwt>; HttpOnly; SameSite=Lax; Path=/ */
                        'Set-Cookie'?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['UserBody'];
                    };
                };
                401: components['responses']['Unauthorized'];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/auth/me': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['UserBody'];
                    };
                };
                401: components['responses']['Unauthorized'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/auth/logout': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie. Idempotent — always succeeds, even with no session. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/stats': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate counters. Soft-fails to zeros for any unreachable slice. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Stats'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/folders': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List/search folders. */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    nhs_number?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['FolderList'];
                    };
                };
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        /** Register a new folder (creates the patient upstream if needed). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateFolder'];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Folder'];
                    };
                };
                422: components['responses']['Validation'];
                503: components['responses']['Upstream'];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/folders/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Folder'];
                    };
                };
                404: components['responses']['NotFound'];
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/folders/{id}/history': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A folder's move history. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['MoveList'];
                    };
                };
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/patients': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['PatientList'];
                    };
                };
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/patients/{nhs}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patient detail. Always 200 — falls back to folder snapshots when the Patient Service is down. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nhs: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['PatientShow'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/places': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    kind?: 'building' | 'room' | 'cabinet';
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['PlacesIndex'];
                    };
                };
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        name: string;
                        /** @enum {string} */
                        kind: 'building' | 'room' | 'cabinet';
                        /** Format: uuid */
                        contained_in_place?: string | null;
                        description?: string | null;
                        capacity?: number | null;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Place'];
                    };
                };
                422: components['responses']['Validation'];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/places/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['PlaceShow'];
                    };
                };
                404: components['responses']['NotFound'];
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/places/{id}/history': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Folder presence history (cabinet intervals; room/building aggregate). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['PlaceHistory'];
                    };
                };
                404: components['responses']['NotFound'];
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/workers': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['WorkerList'];
                    };
                };
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/workers/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Worker detail — folders they moved + all their patients' folders. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['WorkerShow'];
                    };
                };
                404: components['responses']['NotFound'];
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/moves': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['MoveList'];
                    };
                };
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        /** Record a folder move. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateMove'];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Move'];
                    };
                };
                404: components['responses']['NotFound'];
                422: components['responses']['Validation'];
                503: components['responses']['Upstream'];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/moves/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Move'];
                    };
                };
                404: components['responses']['NotFound'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/volumes': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    nhs_number?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['VolumeList'];
                    };
                };
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        nhs_number: string;
                        title: string;
                        /** Format: uuid */
                        cabinet_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Volume'];
                    };
                };
                422: components['responses']['Validation'];
                503: components['responses']['Upstream'];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/volumes/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['VolumeShow'];
                    };
                };
                404: components['responses']['NotFound'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a volume. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        title: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['VolumeShow'];
                    };
                };
                404: components['responses']['NotFound'];
                422: components['responses']['Validation'];
            };
        };
        trace?: never;
    };
    '/api/volumes/{id}/folders': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a folder to the volume (same patient). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: uuid */
                        folder_id: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['VolumeShow'];
                    };
                };
                404: components['responses']['NotFound'];
                422: components['responses']['Validation'];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/volumes/{id}/folders/{folder_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a folder from the volume. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                    folder_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['VolumeShow'];
                    };
                };
                404: components['responses']['NotFound'];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/volumes/{id}/move': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move the whole volume — relocates every member folder, one move event each. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components['parameters']['Id'];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: uuid */
                        to_cabinet_id?: string | null;
                        /** Format: uuid */
                        worker_id?: string | null;
                        moved_by?: string | null;
                        reason?: string | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['VolumeShow'];
                    };
                };
                404: components['responses']['NotFound'];
                422: components['responses']['Validation'];
                503: components['responses']['Upstream'];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/alerts': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geofence alerts — moves that crossed a building boundary. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AlertList'];
                    };
                };
                503: components['responses']['Upstream'];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error?: string;
        };
        ValidationError: {
            errors?: {
                [key: string]: string;
            };
        };
        UserBody: {
            user?: {
                email?: string;
                name?: string;
                role?: string | null;
            };
        };
        Stats: {
            patients?: number;
            folders?: {
                total?: number;
                in_cabinet?: number;
                in_transit?: number;
            };
            places?: {
                buildings?: number;
                rooms?: number;
                cabinets?: number;
            };
            moves_24h?: number;
        };
        Folder: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: uuid */
            patient_id?: string;
            nhs_number?: string;
            patient_name?: string;
            /** Format: uuid */
            cabinet_id?: string | null;
            cabinet_label?: string;
            /** @enum {string} */
            status?: 'in-cabinet' | 'in-transit';
            /** Format: date-time */
            last_moved_at?: string | null;
            notes?: string | null;
            /** Format: uuid */
            volume_id?: string | null;
            volume_title?: string | null;
        };
        CreateFolder: {
            nhs_number: string;
            patient_name?: string | null;
            /** Format: date */
            date_of_birth?: string | null;
            title: string;
            /** Format: uuid */
            cabinet_id?: string | null;
            notes?: string | null;
            /** Format: uuid */
            volume_id?: string | null;
        };
        Patient: {
            /** Format: uuid */
            id?: string;
            nhs_number?: string;
            name?: string;
            date_of_birth?: string | null;
            folder_count?: number;
            source?: string;
        };
        PatientShow: {
            patient?: components['schemas']['Patient'] | null;
            folders?: components['schemas']['Folder'][];
            history?: components['schemas']['Move'][];
            nhs_number?: string;
            patient_service_match?: boolean;
        };
        Place: {
            /** Format: uuid */
            id?: string;
            name?: string;
            place_type?: string;
            /** @enum {string} */
            place_kind?: 'building' | 'room' | 'cabinet' | 'other';
            description?: string | null;
            /** Format: uuid */
            contained_in_place?: string | null;
            container_path?: string;
            capacity?: number | null;
            source?: string;
        };
        Cabinet: components['schemas']['Place'] & {
            folder_count?: number;
        };
        PlacesIndex: {
            query?: string | null;
            kind?: string | null;
            buildings?: components['schemas']['Place'][];
            rooms?: components['schemas']['Place'][];
            cabinets?: components['schemas']['Cabinet'][];
        };
        PlaceShow: components['schemas']['Place'] & {
            folders?: components['schemas']['Folder'][];
        };
        Presence: {
            /** Format: uuid */
            folder_id?: string;
            folder_title?: string;
            /** Format: uuid */
            patient_id?: string;
            nhs_number?: string;
            patient_name?: string;
            /** Format: uuid */
            cabinet_id?: string;
            cabinet_label?: string;
            /** Format: date-time */
            entered_at?: string;
            /** Format: date-time */
            left_at?: string | null;
            entered_reason?: string | null;
            left_reason?: string | null;
        };
        PlaceHistory: components['schemas']['Place'] & {
            presences?: components['schemas']['Presence'][];
        };
        Worker: {
            /** Format: uuid */
            id?: string;
            name?: string;
            role?: string | null;
        };
        WorkerShow: {
            worker?: components['schemas']['Worker'];
            moved_folders?: components['schemas']['Folder'][];
            patient_folders?: components['schemas']['Folder'][];
            moves?: components['schemas']['Move'][];
        };
        Move: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            folder_id?: string;
            folder_title?: string;
            /** Format: uuid */
            patient_id?: string;
            nhs_number?: string;
            patient_name?: string;
            /** Format: uuid */
            from_cabinet_id?: string | null;
            from_cabinet_label?: string;
            /** Format: uuid */
            to_cabinet_id?: string | null;
            to_cabinet_label?: string;
            /** Format: uuid */
            worker_id?: string | null;
            moved_by?: string;
            worker_role?: string | null;
            /** Format: date-time */
            moved_at?: string;
            reason?: string | null;
        };
        CreateMove: {
            /** Format: uuid */
            folder_id: string;
            /** Format: uuid */
            to_cabinet_id?: string | null;
            /** Format: uuid */
            worker_id?: string | null;
            moved_by?: string | null;
            reason?: string | null;
        };
        Volume: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: uuid */
            patient_id?: string;
            nhs_number?: string;
            patient_name?: string;
            /** Format: uuid */
            cabinet_id?: string | null;
            cabinet_label?: string;
            /** @enum {string} */
            status?: 'in-cabinet' | 'in-transit';
            folder_count?: number;
        };
        VolumeShow: components['schemas']['Volume'] & {
            folders?: components['schemas']['Folder'][];
            history?: components['schemas']['Move'][];
        };
        Alert: {
            /** Format: uuid */
            move_id?: string;
            /** Format: uuid */
            folder_id?: string;
            folder_title?: string;
            patient_name?: string;
            nhs_number?: string;
            from_building?: string;
            to_building?: string;
            from_cabinet_label?: string;
            to_cabinet_label?: string;
            moved_by?: string;
            /** Format: date-time */
            moved_at?: string;
            reason?: string | null;
        };
        FolderList: {
            items?: components['schemas']['Folder'][];
            query?: string;
        };
        PatientList: {
            items?: components['schemas']['Patient'][];
            query?: string;
        };
        WorkerList: {
            items?: components['schemas']['Worker'][];
            query?: string;
        };
        MoveList: {
            items?: components['schemas']['Move'][];
            query?: string;
        };
        VolumeList: {
            items?: components['schemas']['Volume'][];
            query?: string;
        };
        AlertList: {
            items?: components['schemas']['Alert'][];
        };
    };
    responses: {
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Error'];
            };
        };
        /** @description Authentication required. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Error'];
            };
        };
        /** @description An upstream Main-X-Service is unreachable. */
        Upstream: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['Error'];
            };
        };
        /** @description Validation failure — each failing field is keyed. */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['ValidationError'];
            };
        };
    };
    parameters: {
        Id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
